# Generated by Django 5.0.4 on 2025-03-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ar_time', models.TimeField()),
                ('ld_time', models.TimeField()),
                ('de_time', models.TimeField()),
                ('experience', models.IntegerField()),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
